### ISSUE TITLE
Crach with quotes "

### ISSUE THREAD

**Issue by lionel-deglise** [agardiner/csv-diff#10]
Thank you for this create tool.

We have a file, iso-8859-1 encoded, containing " in values, so we get this error message : 

```An error occurred opening file /opt/data/catalogue_CdiscountProP30_News.csv.last: Illegal quoting in line 114650.```

I can't help because i don't know Ruby.

**Comment by agardiner** [comment]
You can try setting the encoding when you read the file, by setting the :encoding option. That may or may not help; files are opened and parsed using the CSV library, and this error looks like one you would get when your file contains improperly quoted data. If that is the case, you will need to correct the file.
