### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by scivola** [agardiner/csv-diff#13]
I am looking forward to see the next version of your awesome gem.

The following code raises on Windows OS:

```rb
require "csv-diff"
require "Tempfile"

Tempfile.create do |f1|
  IO.write f1.path, "a\n1"
  Tempfile.create do |f2|
    IO.write f2.path, "a\n2"
    CSVDiff.new f1.path, f2.path, key_fields: "a"
  end
end
```

Because the `create` method try to unlink the temporary file after evaluating its block, but it is impossible to unlink an *open* file on Windows.
(No problem on macOS)

This problem will be solved via #8.
So I can hardly wait for the next version release.

**Comment by agardiner** [comment]
I've just pushed a new release (0.5.0) to Ruby gems.

Cheers,
Adam

**Comment by scivola** [comment]
The above problem was solved. Thank you!
