### ISSUE TITLE
Keyfields are not ignored when containing string values.

### ISSUE THREAD

**Issue by ilpoviertola** [agardiner/csv-diff#14]
Hello,

I am using this gem to diff csv-files which have string values as keys. Gem includes keyfields in the diff altough defined correctly. This happens only when keyfields contain string values. Gem suggests to update keyfields as an outcome.

Any help?

**Comment by agardiner** [comment]
Hi there,
I'm not really able to understand the issue from your description. Could you provide an example of what you mean?

**Comment by ilpoviertola** [comment]
Sorry about very late response and unclear explanation of the issue. My bug is the same described here in the another issue: https://github.com/agardiner/csv-diff/issues/15.

**Comment by hammzj** [comment]
Hey @ilpoviertola, I closed my issue last week and you referenced this issue in there #15. You may be able to close your issue here now too.
