### ISSUE TITLE
Warning on Ruby  2.4.x

### ISSUE THREAD

**Issue by mura2435** [agardiner/csv-diff#5]
Warning appears on line [212](https://github.com/agardiner/csv-diff/blob/master/lib/csv-diff/csv_source.rb#L212) of csv_source.rb

>  warning: constant ::Fixnum is deprecated

Fixnum and Bignum were unified to integer in Ruby 2.4.0(https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/)

May I suggest a modification to the [212](https://github.com/agardiner/csv-diff/blob/master/lib/csv-diff/csv_source.rb#L212)?
` if field.is_a?(Intger)`

**Comment by agardiner** [comment]
Thanks for the bug report and suggested fix. :-)
